#!/usr/bin/env ansible-playbook

---

- hosts: all
  gather_facts: False
  tasks: 
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    
- hosts: all
  become: true
  gather_facts: true

- hosts: web_server
  tasks:
    - name: ensure .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        
    - name: ensure public key exists
      openssh_keypair:
        path: ~/.ssh/id_rsa
        
    - name: get key and store
      shell: cat ~/.ssh/id_rsa.pub
      register: ssh_keys

    - name: deploy keys on all processing_machines
      authorized_key:
        user: root
        key: "{{ ssh_keys.stdout }}"
      delegate_to: "{{ hostvars[item].ansible_ssh_host }}"
      with_items: "{{ groups['processing_machine'] }}"

- hosts: processing_machine
  gather_facts: no
  tasks:
  - name: copy network downloader for nvidia cuda to machine
    synchronize:
      src: cuda-repo-ubuntu1810_10.1.105-1_amd64.deb
      dest: /

- hosts: processing_machine
  strategy: free
  remote_user: root
  roles:
    - processing_machine
          
   

- hosts: etcd_cluster  
  strategy: free
  remote_user: root
  roles:
    - etcd
 
  
- hosts: web_server
  strategy: free
  remote_user: root
  roles:
    - web_server
    


- hosts: web_server
  tasks:
  - name: start pm2 web app on each web server
    command: 'pm2 start --name pink_web_app /web_app/server.js'
  
- hosts: load_balancer
  strategy: free
  remote_user: root
  roles:
    - nginx
    
    
    
  
