---
# tasks file for web_server

- name: Install npm
  apt: 
    name: npm
    update_cache: yes

- name: Install pip
  apt: 
    name: python-pip
    update_cache: yes

- name: Install nodejs
  apt: 
    name: nodejs 
    
- name: Install sshfs
  apt: 
    name: sshfs

   
- name: Copy web app to web server
  synchronize:
      src: web_app
      dest: /
      
- name: Write config template
  template:
    src: config.json.j2
    dest: /web_app/config.json
      
- name: Write upload daemon template
  template:
    src: upload_daemon.py.j2
    dest: /web_app/upload_daemon.py


- name: Install package.json dependencies
  npm:
    path: /web_app
  
- name: Install pm2
  npm:
    name: pm2
    global: yes
    state: present
    
- name: install python etcd
  pip:
    name: python-etcd
    
- name: Stop old server if it exists
  command: pm2 delete pink_web_app
  ignore_errors: yes


- name: create directory for ssh key
  file:
    path: ~/.ssh
    state: directory
    

  


    
  
    

